#' Load and process data to analyze correlation between structural entropy and Indel efficiency.
#'
#' This function reads a TSV file containing structural entropy (e.g., B-factor)
#' measurements for different regions (TL, SL1, SL2, SL3) and corresponding
#' Indel frequencies. It calculates Spearman rank correlations between
#' entropy in each region and Indel frequency, printing these statistics
#' to the console. Additionally, it generates a faceted scatter plot
#' visualizing the relationship, with each facet representing a region,
#' and saves this plot as a PDF.
#'
#' @param input_tsv Path to the input TSV file. This file must contain
#'   columns named "Indel", "TL", "SL1", "SL2", and "SL3". Entropy and Indel
#'   values will be coerced to numeric.
#' @param output_pdf Path to the output PDF file where the generated
#'   scatter plot will be saved.
#' @return Invisibly returns `NULL`. The function's main effects are
#'   printing statistical results to the console and saving a plot to disk.
#'   It will print a warning and return early if insufficient valid data points
#'   are found after cleaning.
#' @import ggplot2
#' @import dplyr
#' @import tidyr
#' @export
library(ggplot2)
library(dplyr)
library(tidyr)

run_correlation_analysis <- function(input_tsv, output_pdf) {
  # 1. Load Data
  # check.names = FALSE prevents R from changing "sequence(sgRNA)" to "sequence.sgRNA."
  df <- read.delim(input_tsv, sep = "\t", check.names = FALSE, na.strings = c("NA", "NaN", ""))
  
  regions <- c("TL", "SL1", "SL2", "SL3")
  
  # 2. Force data types to numeric 
  # This acts as a safety net if any text accidentally leaked into the columns
  df$Indel <- as.numeric(as.character(df$Indel))
  for (r in regions) {
    df[[r]] <- as.numeric(as.character(df[[r]]))
  }
  
  # 3. Clean Data
  # Strictly drop rows that have NAs (e.g., sequences missing Indel data or truncated PDBs)
  df_clean <- drop_na(df, all_of(c(regions, "Indel")))
  
  if (nrow(df_clean) < 3) {
    cat(sprintf("WARNING: Not enough valid data points in %s to run correlations.\n\n", input_tsv))
    return()
  }
  
  # 4. Calculate and Print Spearman Rank Correlation
  cat(sprintf("=== Statistics for: %s ===\n", input_tsv))
  cat(sprintf("Total valid sequences analyzed: %d\n", nrow(df_clean)))
  
  for (r in regions) {
    # exact = FALSE prevents the test from throwing warnings if there are tied values
    stat_test <- cor.test(df_clean[[r]], df_clean$Indel, method = "spearman", exact = FALSE)
    
    rho <- stat_test$estimate
    pval <- stat_test$p.value
    
    cat(sprintf("%-4s vs Indel --> Spearman rho: %6.4f | P-value: %1.4e\n", r, rho, pval))
  }
  cat("\n")
  
  # 5. Reshape Data for Faceted Plotting
  df_long <- pivot_longer(df_clean, cols = all_of(regions), names_to = "Region", values_to = "Entropy")
  # Lock the factor levels so the plot renders left-to-right as TL -> SL1 -> SL2 -> SL3
  df_long$Region <- factor(df_long$Region, levels = regions) 
  
  # 6. Generate the Scatter Plot
  p <- ggplot(df_long, aes(x = Entropy, y = Indel)) +
    geom_point(alpha = 0.6, color = "black", size = 2) +
    # Add a linear trendline just to guide the eye on the overall direction of the data
    geom_smooth(method = "lm", color = "red", linetype = "dashed", se = FALSE) +
    facet_wrap(~ Region, scales = "free_x", nrow = 1) +
    theme_bw() +
    labs(title = sprintf("Entropy vs Indel Efficiency (%s)", input_tsv),
         subtitle = "Evaluating structural flexibility against editing efficiency",
         x = "Averaged Positional Entropy (B-factor)",
         y = "Indel Frequency") +
    theme(strip.text = element_text(size = 12, face = "bold"),
          plot.title = element_text(face = "bold"))
  
  # Save the plot
  ggsave(output_pdf, plot = p, width = 11, height = 4, dpi = 300)
  cat(sprintf("Saved plot to: %s\n\n", output_pdf))
}

# --- Execution Block ---
# Define the target files generated by the Python script
files_to_process <- c("entropy_averages_super_relaxed.tsv", 
                      "entropy_averages_relaxed.tsv", 
                      "entropy_averages_strict.tsv")

for (file in files_to_process) {
  if (file.exists(file)) {
    # Replace .tsv with .pdf for the output file name
    out_name <- gsub(".tsv", "_correlation_plot.pdf", file)
    run_correlation_analysis(file, out_name)
  } else {
    cat(sprintf("File missing, skipping: %s\n", file))
  }
}
