import os

def find_missing_sequences(extracted_txt, reference_txt, missing_out):
    """Compares sequences from an extracted PDB file against a reference file to identify missing sequences.

    This function first loads all unique sequences from the `extracted_txt` file
    (expected to be in "Chain_X: SEQUENCE" format) into a set. Then, it iterates
    through the `reference_txt` file (expected to be a headerless file with one
    sequence per line). Any sequence found in `reference_txt` that is *not* present
    in the set of extracted PDB sequences is considered missing and written to
    the `missing_out` file. Summary statistics are printed to the console.

    Args:
        extracted_txt (str): Path to the file containing sequences extracted from PDB files.
                             Each relevant line should start with "Chain_" and contain
                             the sequence after a colon, e.g., "Chain_A: ATGC...".
        reference_txt (str): Path to the headerless reference file containing target
                             sequences, one per line.
        missing_out (str): Path to the output file where missing sequences
                           (those in `reference_txt` but not in `extracted_txt`)
                           will be written, one per line.

    Returns:
        None: The function writes missing sequences to `missing_out` and prints
              summary statistics to the console. It does not return any value.
              If `extracted_txt` or `reference_txt` are not found, an error
              message is printed and the function returns early.
    """
    # Step 1: Load the extracted PDB sequences into a set
    pdb_sequences = set()
    
    if not os.path.exists(extracted_txt):
        print(f"Error: {extracted_txt} not found.")
        return
        
    with open(extracted_txt, 'r') as f:
        for line in f:
            if line.startswith("Chain_"):
                # Split at the colon and take the second part (the sequence), stripping whitespace
                sequence = line.split(":", 1)[1].strip()
                pdb_sequences.add(sequence)
    
    # Step 2: Compare the headerless file against the set
    if not os.path.exists(reference_txt):
        print(f"Error: {reference_txt} not found.")
        return

    missing_count = 0
    with open(reference_txt, 'r') as ref, open(missing_out, 'w') as out:
        for line in ref:
            target_seq = line.strip()
            
            # Skip empty lines
            if not target_seq:
                continue  
                
            # If the sequence is not in our PDB set, it's missing
            if target_seq not in pdb_sequences:
                out.write(f"{target_seq}\n")
                missing_count += 1
                
    print(f"Comparison complete.")
    print(f"- Unique sequences found in PDB extractions: {len(pdb_sequences)}")
    print(f"- Sequences missing from PDB extractions: {missing_count}")
    print(f"Missing sequences saved to: {missing_out}")


if __name__ == "__main__":
    # Define your filenames here
    EXTRACTED_FILE = "extracted_nucleotides.txt"  # The file generated by the previous script
    REFERENCE_FILE = "file.txt"   # Replace with the actual name of your headerless file
    OUTPUT_FILE = "missing_sequences.txt"         # Where the missing sequences will be saved
    
    find_missing_sequences(EXTRACTED_FILE, REFERENCE_FILE, OUTPUT_FILE)
